import {
  LucideIcon,
  Swords,
  Trophy,
  TrendingUp,
  Award,
  Medal,
  Crown,
  Film,
  Heart,
  MessageSquare,
  Share2,
  Video,
  Save,
  Users,
  UserPlus,
  CalendarDays,
  Repeat,
  Sunrise,
  Sunset,
  Gift,
  PartyPopper,
  Moon,
  Cloudy,
  Sparkles,
  Zap,
  BarChart,
  Eye,
  Camera,
  MapPin,
  Briefcase,
  Star,
} from 'lucide-react';

export type AchievementCategory = 'Performance' | 'Media & Social' | 'Community & Club' | 'Consistency & Fun';

export type Achievement = {
  id: string;
  title: string;
  description: string;
  category: AchievementCategory;
  icon: LucideIcon;
  threshold: number;
};

export const achievements: Achievement[] = [
  // Performance (1-30)
  { id: 'perf_1', title: 'First Match Played', description: 'Step onto the court for your first official match.', category: 'Performance', icon: Swords, threshold: 1 },
  { id: 'perf_2', title: '5 Matches Played', description: 'You\'re getting into the swing of things.', category: 'Performance', icon: Swords, threshold: 5 },
  { id: 'perf_3', title: '10 Matches Played', description: 'Double digits! Keep up the great work.', category: 'Performance', icon: Swords, threshold: 10 },
  { id: 'perf_4', title: '25 Matches Played', description: 'A true court regular.', category: 'Performance', icon: Swords, threshold: 25 },
  { id: 'perf_5', title: '50 Matches Played', description: 'Half a century of matches!', category: 'Performance', icon: Swords, threshold: 50 },
  { id: 'perf_6', title: '100 Matches Played', description: 'Welcome to the centurion club.', category: 'Performance', icon: Medal, threshold: 100 },
  { id: 'perf_7', title: 'First Win', description: 'Savor that first taste of victory.', category: 'Performance', icon: Trophy, threshold: 1 },
  { id: 'perf_8', title: '5 Wins', description: 'You\'re building a winning habit.', category: 'Performance', icon: Trophy, threshold: 5 },
  { id: 'perf_9', title: '10 Wins', description: 'Ten victories under your belt.', category: 'Performance', icon: Trophy, threshold: 10 },
  { id: 'perf_10', title: '25 Wins', description: 'A formidable opponent on the court.', category: 'Performance', icon: Trophy, threshold: 25 },
  { id: 'perf_11', title: 'First Ranked Match', description: 'Put your skills to the test in a ranked game.', category: 'Performance', icon: BarChart, threshold: 1 },
  { id: 'perf_12', title: 'First Win Against Higher Level', description: 'Punch above your weight and win.', category: 'Performance', icon: TrendingUp, threshold: 1 },
  { id: 'perf_13', title: 'Win Streak x3', description: 'Three wins in a row. You\'re on fire!', category: 'Performance', icon: Zap, threshold: 3 },
  { id: 'perf_14', title: 'Win Streak x5', description: 'Five consecutive wins! Unstoppable.', category: 'Performance', icon: Zap, threshold: 5 },
  { id: 'perf_15', title: 'Win Streak x10', description: 'A perfect ten-match winning streak.', category: 'Performance', icon: Zap, threshold: 10 },
  { id: 'perf_16', title: 'First Tiebreak Win', description: 'Clutch performance under pressure.', category: 'Performance', icon: Sparkles, threshold: 1 },
  { id: 'perf_17', title: 'Perfect Match', description: 'Win a match without losing a single game.', category: 'Performance', icon: Award, threshold: 1 },
  { id: 'perf_18', title: 'Comeback Win', description: 'Win a match after losing the first set.', category: 'Performance', icon: Repeat, threshold: 1 },
  { id: 'perf_19', title: 'Played All Court Positions', description: 'Show your versatility on the court.', category: 'Performance', icon: Users, threshold: 4 },
  { id: 'perf_20', title: 'Mixed Match Played', description: 'Team up in a mixed doubles match.', category: 'Performance', icon: Users, threshold: 1 },
  { id: 'perf_21', title: 'Doubles Specialist', description: 'Play 25 doubles matches.', category: 'Performance', icon: Users, threshold: 25 },
  { id: 'perf_22', title: 'Singles Challenger', description: 'Play your first singles match.', category: 'Performance', icon: UserPlus, threshold: 1 },
  { id: 'perf_23', title: 'Played with 10 Different Players', description: 'Expand your network on the court.', category: 'Performance', icon: Users, threshold: 10 },
  { id: 'perf_24', title: 'Played with 25 Different Players', description: 'A true social butterfly of the padel world.', category: 'Performance', icon: Users, threshold: 25 },
  { id: 'perf_25', title: 'Played All Club Courts', description: 'You\'ve conquered every court in your club.', category: 'Performance', icon: MapPin, threshold: 1 },
  { id: 'perf_26', title: 'First Tournament Match', description: 'Enter the competitive arena.', category: 'Performance', icon: Medal, threshold: 1 },
  { id: 'perf_27', title: 'Tournament Winner', description: 'Emerge as the champion of a tournament.', category: 'Performance', icon: Crown, threshold: 1 },
  { id: 'perf_28', title: 'Top 10 Club Ranking', description: 'Break into the top 10 of your club.', category: 'Performance', icon: BarChart, threshold: 1 },
  { id: 'perf_29', title: 'Top 5 Club Ranking', description: 'Join the elite top 5 players in your club.', category: 'Performance', icon: BarChart, threshold: 1 },
  { id: 'perf_30', title: 'Club Champion', description: 'Become the number one ranked player in your club.', category: 'Performance', icon: Crown, threshold: 1 },

  // Media & Social (31-60)
  { id: 'media_1', title: 'First Highlight Created', description: 'Capture and save your first highlight.', category: 'Media & Social', icon: Film, threshold: 1 },
  { id: 'media_2', title: '5 Highlights', description: 'Create a collection of your best moments.', category: 'Media & Social', icon: Film, threshold: 5 },
  { id: 'media_3', title: '10 Highlights', description: 'Your personal highlight reel is growing.', category: 'Media & Social', icon: Film, threshold: 10 },
  { id: 'media_4', title: '25 Highlights', description: 'A library of your on-court heroics.', category: 'Media & Social', icon: Film, threshold: 25 },
  { id: 'media_5', title: 'Highlight of the Week', description: 'Your clip was featured as Highlight of the Week.', category: 'Media & Social', icon: Star, threshold: 1 },
  { id: 'media_6', title: 'First Like Received', description: 'Someone appreciated your content!', category: 'Media & Social', icon: Heart, threshold: 1 },
  { id: 'media_7', title: '10 Likes Received', description: 'Your content is gaining popularity.', category: 'Media & Social', icon: Heart, threshold: 10 },
  { id: 'media_8', title: '50 Likes Received', description: 'Becoming a fan favorite.', category: 'Media & Social', icon: Heart, threshold: 50 },
  { id: 'media_9', title: '100 Likes Received', description: 'A social media star in the making.', category: 'Media & Social', icon: Heart, threshold: 100 },
  { id: 'media_10', title: 'First Comment Received', description: 'Start a conversation around your game.', category: 'Media & Social', icon: MessageSquare, threshold: 1 },
  { id: 'media_11', title: '25 Comments Received', description: 'Your content is sparking discussions.', category: 'Media & Social', icon: MessageSquare, threshold: 25 },
  { id: 'media_12', title: '50 Comments Received', description: 'A hub of community interaction.', category: 'Media & Social', icon: MessageSquare, threshold: 50 },
  { id: 'media_13', title: 'First Video Viewed 100x', description: 'Your highlight reached 100 views.', category: 'Media & Social', icon: Eye, threshold: 100 },
  { id: 'media_14', title: 'First Shared Highlight', description: 'Your skills are worth sharing.', category: 'Media & Social', icon: Share2, threshold: 1 },
  { id: 'media_15', title: 'Most Viewed Highlight of the Day', description: 'Go viral for a day!', category: 'Media & Social', icon: TrendingUp, threshold: 1 },
  { id: 'media_16', title: 'Club Highlight Star', description: 'Have 5 highlights featured in the club feed.', category: 'Media & Social', icon: Star, threshold: 5 },
  { id: 'media_17', title: 'Uploaded First Match Video', description: 'Share a full match for analysis or posterity.', category: 'Media & Social', icon: Video, threshold: 1 },
  { id: 'media_18', title: 'Media Streak', description: 'Create highlights from 3 consecutive matches.', category: 'Media & Social', icon: Camera, threshold: 3 },
  { id: 'media_19', title: 'Top Media Creator', description: 'Be the most prolific media creator in your club.', category: 'Media & Social', icon: Crown, threshold: 1 },
  { id: 'media_20', title: 'Saved First Highlight', description: 'Save a highlight from another player.', category: 'Media & Social', icon: Save, threshold: 1 },
  { id: 'media_21', title: 'Highlight Watched 10 Times', description: 'Your clip has been watched 10 times.', category: 'Media & Social', icon: Eye, threshold: 10 },
  { id: 'media_22', title: 'Highlight Watched 50 Times', description: 'Your clip has been watched 50 times.', category: 'Media & Social', icon: Eye, threshold: 50 },
  { id: 'media_23', title: 'Highlight Watched 100 Times', description: 'Your clip has been watched 100 times.', category: 'Media & Social', icon: Eye, threshold: 100 },
  { id: 'media_24', title: 'First Event Media', description: 'Capture a moment from a club event.', category: 'Media & Social', icon: PartyPopper, threshold: 1 },
  { id: 'media_25', title: 'First Profile Media', description: 'Personalize your profile with content.', category: 'Media & Social', icon: UserPlus, threshold: 1 },
  { id: 'media_26', title: 'Highlight With Partner', description: 'Create a highlight featuring you and your partner.', category: 'Media & Social', icon: Users, threshold: 1 },
  { id: 'media_27', title: 'Highlight With New Player', description: 'Share a moment with someone new.', category: 'Media & Social', icon: UserPlus, threshold: 1 },
  { id: 'media_28', title: 'Most Liked Highlight (week)', description: 'Earn the most likes in the club this week.', category: 'Media & Social', icon: Heart, threshold: 1 },
  { id: 'media_29', title: 'Media Explorer', description: 'Watch 25 different highlights.', category: 'Media & Social', icon: Video, threshold: 25 },
  { id: 'media_30', title: 'Video Veteran', description: 'Upload 10 full match videos.', category: 'Media & Social', icon: Video, threshold: 10 },

  // Community & Club (61-80)
  { id: 'comm_1', title: 'Joined First Club', description: 'Welcome to the community!', category: 'Community & Club', icon: Award, threshold: 1 },
  { id: 'comm_2', title: 'Joined Second Club', description: 'Expanding your padel horizons.', category: 'Community & Club', icon: Award, threshold: 2 },
  { id: 'comm_3', title: 'Played in 3 Clubs', description: 'A traveling padel enthusiast.', category: 'Community & Club', icon: Briefcase, threshold: 3 },
  { id: 'comm_4', title: 'First Match With New Player', description: 'Welcome a newcomer to the court.', category: 'Community & Club', icon: UserPlus, threshold: 1 },
  { id: 'comm_5', title: 'Event Participant', description: 'Join your first club event.', category: 'Community & Club', icon: PartyPopper, threshold: 1 },
  { id: 'comm_6', title: 'Event Winner', description: 'Win a club event.', category: 'Community & Club', icon: Trophy, threshold: 1 },
  { id: 'comm_7', title: 'Organizer Helper', description: 'Help organize a club match or event.', category: 'Community & Club', icon: Users, threshold: 1 },
  { id: 'comm_8', title: 'Club Regular', description: 'Play 10 matches at the same club.', category: 'Community & Club', icon: Repeat, threshold: 10 },
  { id: 'comm_9', title: 'Weekly Club Player', description: 'Play at your club every week for a month.', category: 'Community & Club', icon: CalendarDays, threshold: 4 },
  { id: 'comm_10', title: 'Monthly Club Player', description: 'Play at your club every month for 6 months.', category: 'Community & Club', icon: CalendarDays, threshold: 6 },
  { id: 'comm_11', title: 'First Club Post Interaction', description: 'Engage with your club\'s feed.', category: 'Community & Club', icon: MessageSquare, threshold: 1 },
  { id: 'comm_12', title: 'First Club Announcement Read', description: 'Stay up to date with club news.', category: 'Community & Club', icon: Eye, threshold: 1 },
  { id: 'comm_13', title: 'Club Loyalist', description: 'Be a member of a single club for a year.', category: 'Community & Club', icon: Medal, threshold: 1 },
  { id: 'comm_14', title: 'Played With Club Manager', description: 'Play a match with the club manager.', category: 'Community & Club', icon: Users, threshold: 1 },
  { id: 'comm_15', title: 'Cross-Club Match', description: 'Play against a member from another club.', category: 'Community & Club', icon: Swords, threshold: 1 },
  { id: 'comm_16', title: 'Community Builder', description: 'Invite 5 new players to the app.', category: 'Community & Club', icon: Users, threshold: 5 },
  { id: 'comm_17', title: 'Matchmaker', description: 'Organize 10 group matches.', category: 'Community & Club', icon: UserPlus, threshold: 10 },
  { id: 'comm_18', title: 'Newcomer Welcomer', description: 'Play with 5 players in their first match.', category: 'Community & Club', icon: UserPlus, threshold: 5 },
  { id: 'comm_19', title: 'Veteran Member', description: 'Be a club member for over 2 years.', category: 'Community & Club', icon: Medal, threshold: 1 },
  { id: 'comm_20', title: 'Club Legend', description: 'Play 200 matches at the same club.', category: 'Community & Club', icon: Crown, threshold: 200 },

  // Consistency & Fun (81-100)
  { id: 'cons_1', title: 'Played 2 Weeks in a Row', description: 'Consistency is key.', category: 'Consistency & Fun', icon: Repeat, threshold: 2 },
  { id: 'cons_2', title: 'Played 4 Weeks in a Row', description: 'A month of consistent play!', category: 'Consistency & Fun', icon: Repeat, threshold: 4 },
  { id: 'cons_3', title: 'Played 8 Weeks in a Row', description: 'Two months of dedication!', category: 'Consistency & Fun', icon: Repeat, threshold: 8 },
  { id: 'cons_4', title: 'Monthly Active Player', description: 'Play at least one match every month for a year.', category: 'Consistency & Fun', icon: CalendarDays, threshold: 12 },
  { id: 'cons_5', title: 'Yearly Active Player', description: 'Be an active player for a full year.', category: 'Consistency & Fun', icon: CalendarDays, threshold: 1 },
  { id: 'cons_6', title: 'Comeback Player', description: 'Return to the court after a month-long break.', category: 'Consistency & Fun', icon: TrendingUp, threshold: 1 },
  { id: 'cons_7', title: 'Early Bird', description: 'Play a match before 8 AM.', category: 'Consistency & Fun', icon: Sunrise, threshold: 1 },
  { id: 'cons_8', title: 'Night Owl', description: 'Play a match after 10 PM.', category: 'Consistency & Fun', icon: Moon, threshold: 1 },
  { id: 'cons_9', title: 'Weekend Warrior', description: 'Play a match every weekend for a month.', category: 'Consistency & Fun', icon: Swords, threshold: 4 },
  { id: 'cons_10', title: 'Rainy Day Player', description: 'Don\'t let the weather stop you (on a covered court).', category: 'Consistency & Fun', icon: Cloudy, threshold: 1 },
  { id: 'cons_11', title: 'Holiday Match', description: 'Play a match on a public holiday.', category: 'Consistency & Fun', icon: PartyPopper, threshold: 1 },
  { id: 'cons_12', title: 'Birthday Match', description: 'Celebrate your birthday on the court.', category: 'Consistency & Fun', icon: Gift, threshold: 1 },
  { id: 'cons_13', title: 'First Match of the Year', description: 'Start the year off right.', category: 'Consistency & Fun', icon: Sparkles, threshold: 1 },
  { id: 'cons_14', title: 'Last Match of the Year', description: 'Finish the year with a game.', category: 'Consistency & Fun', icon: Sparkles, threshold: 1 },
  { id: 'cons_15', title: 'Friendly Rival', description: 'Play against the same opponent 10 times.', category: 'Consistency & Fun', icon: Swords, threshold: 10 },
  { id: 'cons_16', title: 'Played With Same Partner 10x', description: 'Build a strong partnership.', category: 'Consistency & Fun', icon: Users, threshold: 10 },
  { id: 'cons_17', title: 'Lucky Win', description: 'Win a match with a final score of 7-6 in the last set.', category: 'Consistency & Fun', icon: Sparkles, threshold: 1 },
  { id: 'cons_18', title: 'Underdog Victory', description: 'Beat a player ranked significantly higher.', category: 'Consistency & Fun', icon: TrendingUp, threshold: 1 },
  { id: 'cons_19', title: 'Match Marathon', description: 'Play 3 matches in a single day.', category: 'Consistency & Fun', icon: Zap, threshold: 3 },
  { id: 'cons_20', title: 'Ultimate Padel Addict', description: 'Play 200 matches in a year.', category: 'Consistency & Fun', icon: Crown, threshold: 200 },
];
